### ISSUE TITLE
Unable to find modules for some sources, how to fix it?

### ISSUE THREAD

**Issue by Mecil9** [FilledStacks/responsive_builder#10]
pubspec.yaml:
 dependencis:
         .......
         responsive_builder: ^0.1.5

console print error:
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:responsive_builder/responsive_builder.dart';` from web_router_demo|lib/widgets/navigation_bar/navigation_bar.dart at 2:1

Failed after 88ms

in file import :

import 'package:flutter/material.dart';
import 'package:responsive_builder/responsive_builder.dart';
import 'package:web_router_demo/widgets/navigation_bar/navigation_bar_mobile.dart';
import 'package:web_router_demo/widgets/navigation_bar/navigation_bar_tablet_desktop.dart';

class NavigationBar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ScreenTypeLayout(
      mobile: NavigationBarMobile(),
      tablet: NavigationBarTableDesktop(),
    );
  }
}

?????

**Comment by Mecil9** [comment]
fix it, must be restart vscode.......

**Comment by syedqbuster** [comment]
getting same issue how did u fix that ?

**Comment by FilledStacks** [comment]
@syedqbuster he restarted vs code. What modules are you having a problem with?

**Comment by syedqbuster** [comment]
I tried restart my android studio but getting same issue,,

**Comment by syedqbuster** [comment]
@FilledStacks This is my pubsec.yml look like
  
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  responsive_builder: ^0.1.5

Facing this issue

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:responsive_builder/responsive_builder.dart';` from demoapp|lib/main.dart at 4:1


Failed after 90ms

**Comment by FilledStacks** [comment]
Update the package to the latest 0.1.9, 
- run flutter pub outdated, see what's out of date. Update those.
- run flutter clean 
- flutter pub get 
- try again.

**Comment by syedqbuster** [comment]
@FilledStacks earlier i used latest version, and got the same issue then i downgrade and tried of all version still getting this issue. 
and also I did the same step.
Is it supported for web project ??
