### ISSUE TITLE
different results from the same code

### ISSUE THREAD

**Issue by vinnytwice** [FilledStacks/responsive_builder#13]
Hi, thanks for the plugin and the tutorials.
I'm following  your responsive web tutorial and I'm experiencing a different behaviour from the sample code from your flutter web_part3 . Basically when resizing the Chrome window to the point that is tablet view the CallToAction takes the whole horizontal space as when on mobile, but the NavBar hasn't changed to mobile yet. In your code the size stays the same as when in Desktop.
I checked the code file by file and seems to be all the same.
Could you please have a look at my code  at https://github.com/vinnytwice/flutter_web_test ?
Thank you very much again.
Cheers.

**Comment by FilledStacks** [comment]
Hi @vinnytwice I won't be able to look at your code. I have tons of internal code to review at the moment. The widget does a very simple check to see the width then returns a widget based on that. Maybe you adjusted your break points?

**Comment by vinnytwice** [comment]
Hi, no worries, I understand. I'll figure it out but I just  followed all the steps..so no I haven't ..
Thank you anyways.
Cheers
