### ISSUE TITLE
Devices ScreenType Enum - use lowerCamel case

### ISSUE THREAD

**Issue by hramnathnayak** [FilledStacks/responsive_builder#15]
It is recommended to use lowerCamelCase for enum values. Can we please have the enum values on enum DeviceScreenType changed to lowerCamel case ?

https://dart.dev/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names

**Comment by FilledStacks** [comment]
Sure, I can do that. I'll keep the old ones and mark as deprecated then use the new ones going forward. I'll do it in a few hours when I'm busy waiting for my code recording to export.

**Comment by FilledStacks** [comment]
Fixed in 0.1.8
