### ISSUE TITLE
BUG: Breakpoints are not working properly 

### ISSUE THREAD

**Issue by ImDeZz** [FilledStacks/responsive_builder#16]
Hi,

I had a bit of a trouble on Flutter web, with the package. I needed to add custom breakpoints. But my mobile breakpoint did not seem to work.

I looked into the code, and found a bug in the _getDeviceType function.

![image](https://user-images.githubusercontent.com/18382875/81499017-9e968300-92c8-11ea-9719-3d28cddf3047.png)

If the breakpoints are matching with the type mobile, it will go through the defaults.

Proposed solution: 
![image](https://user-images.githubusercontent.com/18382875/81499059-ef0de080-92c8-11ea-9447-b9100d0e4338.png)

**Comment by FilledStacks** [comment]
Thanks for the detailed issue. It's fixed in 0.1.8 :)

**Comment by FilledStacks** [comment]
Hi @ImDeZz please stay on 0.1.8 this fix introduces other bugs so I reverted on 0.1.9 until I add all the unit tests for the current functionality. Then I'll add the functionality you're asking for while keeping the other in tact.

**Comment by FilledStacks** [comment]
0.2.0 should have this fixed now. It will return mobile if no breakpoint is defined.
