### ISSUE TITLE
Allow platform specific layouts

### ISSUE THREAD

**Issue by fotiDim** [FilledStacks/responsive_builder#17]
It would be nice to be able to provide a different layout for iOS, Android and web. Something like:

```
ScreenTypeLayout(
  // Platforms
  ios: Container(color:Colors.white)
  android: Container(color:Colors.black)
  web: Container(color:Colors.green)
  ...
  // Screen types
  mobile: Container(color:Colors.blue)
  tablet: Container(color: Colors.yellow),
  desktop: Container(color: Colors.red),
  watch: Container(color: Colors.purple),
);
```

There is some overlap with the existing screen types but the platform is another dimension of the layout and you can have any combination of "platform" and "screen type" there. It could even be more fine grained like:
```
desktopWeb: Container(color:Colors.red),
mobileWeb: Container(color:Colors.blue)
```

**Comment by FilledStacks** [comment]
I think having a separate builder widget would probably work better. That way you can Have

```dart
ScreenTypeLayout.builder(
mobile: (context) => PlatformLayoutBuilder(
   ios: (context) => IosMobileLayout(),
   web: (context) => WebMobileLayout(),
  )
)
```

Similar to how you can define orientation specific layouts and the ones that don't have it just stays the same. When I get some time I'll add something like that.

**Comment by fotiDim** [comment]
@FilledStacks does it makes sense to use [this package](https://pub.dev/packages/flutter_platform_widgets) for the implementation?

**Comment by FilledStacks** [comment]
@fotiDim yes. That would work if you want platform specific design styles for widgets. In the case of for instance Web, Desktop, Mobile or Watch, that won't work. But it can definitely be used as well.

**Comment by FilledStacks** [comment]
We won't be adding this functionality at the moment. We might build a separate package for this if we see this is a required functionality in our client applications.
