### ISSUE TITLE
ipadOs is currently classified as Desktop

### ISSUE THREAD

**Issue by lcsvcn** [FilledStacks/responsive_builder#18]
**ipadOs** is classified as **Desktop**

Since all desktop/notebook have width > height and all tablets has height > width, I think **IpadOS** fits better if classified as **Tablet** 

Maybe should be nice to change this in the next update

**Comment by FilledStacks** [comment]
You can add custom break points :) Check the readme and set the break points how you'd like it to be.

**Comment by lcsvcn** [comment]
Thanks, it worked :)

**Comment by FilledStacks** [comment]
@lcsvcn thanks for sharing your breakpoints. yeah i had the oposite problem with a smaller android tablet where it was classified as a phone so it showed the mobile UI. It'll always be a custom break point solution. Happy you solved it!
