### ISSUE TITLE
Example with OrientationLayoutBuilder where the Screens don't reload when orientation change

### ISSUE THREAD

**Issue by sbosell** [FilledStacks/responsive_builder#20]
Can you post an example of an orientation change that doesn't reload the entire page.  If the orientation changes it shouldn't necessarily reload the entire screen, should just reload the UI.  An example might be loading list of items.  It may not need/require/want to reload the list of items on orientation change (if it is a network call then slow), only change the layout.  This example would be really nice to have and review.

By the way, great package.

**Comment by FilledStacks** [comment]
When the orientation changes the builder will be called in Flutter. That means our builder will be called. We follow flutters "natural" rebuild structure since it's been optimized to handle multiple rebuilds when they are required.
