### ISSUE TITLE
how to add to pubspec yaml???

### ISSUE THREAD

**Issue by fisforfaheem** [FilledStacks/responsive_builder#21]
pleas ehelp

**Comment by FilledStacks** [comment]
run the flutter create command

**Comment by fisforfaheem** [comment]
no i am aunable to add it to yaml as it sucks and says soemthig wrong

**Comment by FilledStacks** [comment]
You don't add it to the yaml. You run the flutter create command in the src folder to generate the yaml file.

**Comment by fisforfaheem** [comment]
ahahn

**Comment by felipecastrosales** [comment]
Create your project and add in dependencies:
  responsive_builder: ^0.3.0

Simple!

**Comment by fisforfaheem** [comment]
Done. ok sir
1
