### ISSUE TITLE
Support for null-safety

### ISSUE THREAD

**Issue by bierbaumtim** [FilledStacks/responsive_builder#22]
Since Dart 2.12.0 beta landed in flutter beta channel, which brings sound null-safety it would be nice to have null-safety support on this package. This would enable everyone to start migrating their apps to null-safety. 

I also would like to work on this and will open an pull request tomorrow.

**Comment by FilledStacks** [comment]
@bierbaumtim I totally agree. That would be awesome! I appreciate the willingness to help out.
