### ISSUE TITLE
Sizedbox in how to set responsive height and width and text fontSize responsive

### ISSUE THREAD

**Issue by ashishoffice** [FilledStacks/responsive_builder#25]
Can you explain me

**Comment by FilledStacks** [comment]
I don't know what you're asking but I'll throw some random facts at you:

1. You can use the `getValueForScreenType<T>` to return a different value based on the screen its on.

```dart
SizedBox(
width: getValueForScreenType<double>(
                      context: context,
                      mobile: 30,
                      tablet: 60,
                    ),
)
```

The above will return a SizedBox with width 30 on a mobile device and 60 on a tablet sized device. 

2. You can use [screenUtil](https://pub.dev/packages/flutter_screenutil) for your font sizing functionality
3. You can use the MediaQuery if you want your SizedBox to react with the screen size changing.
