### ISSUE TITLE
Migrate to sound null safety 

### ISSUE THREAD

**Issue by lcsvcn** [FilledStacks/responsive_builder#27]
Description:

- Migrate to sound null safety
- Bump up package version to stable (1.2.0 or 2.0.0)

Hi I would like to know what is the state of the null safety pre-release. When it will be available as stable release.

**Comment by FilledStacks** [comment]
hey, there's no progress on this. 

I will try and make time to update this today.

**Comment by FilledStacks** [comment]
This is pushed in 0.4.1
