### ISSUE TITLE
Unstable on Windows

### ISSUE THREAD

**Issue by KKimj** [FilledStacks/responsive_builder#31]
Hello, 
Thanks your effort for this awesome package!
_It works perfectly on the web. thanks!_
I found an unintentional behavior on Windows, When I adjusted the __height instead of the width.__
Please check

```dart
         ScreenTypeLayout(
                breakpoints:
                    ScreenBreakpoints(tablet: 773, desktop: 774, watch: 300),
                mobile: Container(
                  color: Colors.blue,
                  child: Center(child: Text('mobile')),
                ),
                // tablet: Container(
                //   color: Colors.yellow,
                //   child: Center(child: Text('tablet')),
                // ),
                desktop: Container(
                  color: Colors.red,
                  child: Center(child: Text('desktop')),
                ),
                watch: Container(
                  color: Colors.purple,
                  child: Center(child: Text('watch')),
                ),
              ),
```

## Normal screen1 ( mobile size )

![image](https://user-images.githubusercontent.com/40026920/118350781-920bd100-b593-11eb-9239-df56ad80c56e.png)

## Unintentional screen2 ( just adjust height of screen1 )

![image](https://user-images.githubusercontent.com/40026920/118350784-959f5800-b593-11eb-9697-0233e5f634a9.png)

Thanks!!

**Comment by disparta** [comment]
@KKimj Have you found a solution for this? I'm having a similar issue on mac.

<img width="1440" alt="Screenshot 2021-07-31 at 13 36 43" src="https://user-images.githubusercontent.com/17022203/127738791-f5d25abd-c4c9-4895-97d9-30375b188437.png">

@FilledStacks is there a fix on the way for this?

**Comment by FilledStacks** [comment]
I have not looked at this. I'm adding it too my list to fix up. Will report back soon.
