### ISSUE TITLE
Widgets Rebuilding when changing window size in web

### ISSUE THREAD

**Issue by romaan-khan** [FilledStacks/responsive_builder#52]
Widgets are rebuilding when changing window size. How do we avoid this

**Comment by muhamadirwan99** [comment]
I have the same issue, how to solve it?

**Comment by FilledStacks** [comment]
Hi, this is how it's expected to work. 

Flutter rebuilds are very effective, and happens all the time. 

- when the notification tray open up
- When the keyboard opens up
- When you get a call
- When a dialog shows up
- When a bottom sheet shows up

Are you experiencing performance issues with this?

**Comment by amrgetment** [comment]
@FilledStacks What is the right approach to keep form data like text field when resizing ?

**Comment by FilledStacks** [comment]
@amrgetment I haven't had to do that, I would say simply using a fixed SizedBox would work? I don't think Flutter would automatically resize a sizedBox

**Comment by amrgetment** [comment]
I think we can use restoration for the state :
https://docs.flutter.dev/platform-integration/android/restore-state-android#overview

**Comment by FilledStacks** [comment]
I'm totally lost with what you're looking for with this issue. 

1. Are you looking for a solution to avoid minor rebuilds of the widget tree when resizing?
2. Are you looking for a way to keep text field the same size when resizing?
3. Are you looking for a solution to restore state from the backend?

An issue can only have one, it makes it easier for me to hellp. 

If the original issue for this is complete please close this one and start a new one. That way anyone from the community can also help.

**Comment by amrgetment** [comment]
only textfield text should be there after rebuilding, I fixed my issue, but I am not the author of this issue

**Comment by FilledStacks** [comment]
Got it. 

Then I'll close this issue.
