### ISSUE TITLE
Passing breakpoints through context?

### ISSUE THREAD

**Issue by crizant** [FilledStacks/responsive_builder#6]
Currently if we need custom breakpoints, we will need to provide the `ScreenBreakpoints` object to every `ScreenTypeLayout` calls. It would be nice if we can use something like `BreakpointProvider` to provide it at the topmost of widget tree, then every instance of `ScreenTypeLayout` can get it internally.

**Comment by FilledStacks** [comment]
That would definitely be very useful. You should add it :)

**Comment by FilledStacks** [comment]
@crizant Not passing through context but now you can set the breakpoints globally using `ResponsiveSizingConfig`. 

[Example on read me](https://pub.dev/packages/responsive_builder#global-screen-breakpoints)
